id = "snakemake"
name = "Snakemake"
version = "0.2.0"
schema_version = 1
authors = ["Louis Vignoli <louis.vignoli@gmail.com>"]
description = "Grammar for snakemake files"
repository = "https://github.com/lvignoli/zed-snakemake"

[grammars.snakemake]
repository = "https://github.com/osthomas/tree-sitter-snakemake"
commit = "e909815acdbe37e69440261ebb1091ed52e1dec6"
